### ISSUE TITLE
[Feature Request] biosnds7.bin, biosnds9.bin and firmware.bin usage

### ISSUE THREAD

**Issue by ghost** [libretro/desmume#18]
In the standalone version of DeSmuME you can use these files and boot to the BIOS before you start a game just like how it functions on a real DS.

Would it be possible to implement/backport this from the standalone for use in the Libretro core?
The standalone also features the option to save/load changes made in the firmware to a separate file which resides in the Battery folder.

This is actually the only thing I miss in the Libretro core being able to use the BIOS files.

Thanks in advance!

**Comment by bearoso** [comment]
The Desmume core recommends you don't do this because it doesn't have good support for it. It shouldn't be too hard, though.

**Comment by TheLocoBandito** [comment]
Thanks for your reply @bearoso 

I just thought now would be a good time to implement this since the current DeSmuME core is up to par with the TASVideos/desmume repo these days.

I didn't know using the original BIOS files wasn't recommended, haven't really noticed something wrong when used in the standalone version, it works perfectly fine and it's a nice addition to an authentic experience.

I would like to point out though that the core is pretty much flawless as it is, and this is just a suggestion.
It's nice to boot up a game to the DS menu and see your name and click the game icon to start the game.

**Comment by fr500** [comment]
It should be easy, just add RETRO_ENVIRONMENT_SUPPORTS_NO_GAME in retro_set_environment (so it shows a "Start Core" option) in the menu.

Then in retro_load_game handle the case where no game is passed properly.

**Comment by bearoso** [comment]
Here's the thing:
- Desmume core doesn't allow booting into BIOS without a game, the code assumes one is there, so you need one of those.
- You'll need bios9.bin bios7.bin and firmware.bin in your system folder.
- I couldn't get the game to boot from the BIOS screen in jit mode, and the source code indicates it is hit or miss with the jit, so it's interpreter mode only.
- I added two options, one just globally enables every firmware file and the bios swi, the other allows booting into the bios interface. The options are getting a little cluttered without having submenus, so I was reluctant to add each option individually.

**Comment by TheLocoBandito** [comment]
Thank you @bearoso 
It works beautifully, AMAZING JOB!

There is only one thing left for this feature to be complete, the standalone can save changes made in the firmware to a firmware.dfc file which is saved/loaded to/from the Battery folder.

Would it be possible for the core to utilize the saves folder for the firmware.dfc file?
The option in the standalone version of DeSmuME is called _Load User Settings from file_

**Comment by bearoso** [comment]
Done. Enabling it was just a flag.

**Comment by TheLocoBandito** [comment]
@bearoso 
You Came, You Saw, You Conquered!

Thanks for all you have done, now there is no reason to stay with the standalone for me anymore.

God bless you sonny!
