### ISSUE TITLE
Resuming content restarts the game

### ISSUE THREAD

**Issue by 777sha** [libretro/desmume#19]
Using the latest libretro core of desmume on windows 10 x64

Sometimes after toggling quick menu and hitting "resume" restarts the game from the beggining.

**Comment by bearoso** [comment]
Can't reproduce this. Are you sure you're not just hitting down while you're in the menu? Or maybe your controller is too sensitive and scrolls accidentally?

**Comment by 777sha** [comment]
It's not a misspress I tested multiple times and it happens - but not with all roms it seems ?.. (like it happens with dawn of sorrow, elite beat agents, pokemon soul silver but not with order of ecclesia from what I have tested - all of these are EU roms)

I provided a log of this occuring, if that can help https://pastebin.com/R407HDa8

**Comment by bearoso** [comment]
So you can toggle the menu on and off and it eventually resets? Do you have to hit the resume option or does the hotkey (F1) do the same.

**Comment by 777sha** [comment]
OK I figured it out.......... one of the controller shortcuts to toggle the menu in RetroArch is L R START SELECT. Which is also a command to soft reset the DS  🤦‍♂️
