### ISSUE TITLE
OpenGL: Shaders are broken, Black screenshots.

### ISSUE THREAD

**Issue by bearoso** [libretro/desmume#2]
Probably has to do with OpenGL state from the core changing Retroarch's expectations.

**Comment by twinaphex** [comment]
That's odd, shaders seem to work fine for me on Windows 10.

**Comment by bearoso** [comment]
I think I fixed the shader issue. Screenshots still broken in OpenGL mode.

**Comment by Tatsuya79** [comment]
Screenshots are working for me with GL rasterizer, 576p multisample, smoothing with a Lanczo shader pass+ DS colours on top.
win7 x64 nvidia 770

**Comment by bearoso** [comment]
Screenshots only work when "Enable Hardware Shared Context" is enabled. Or basically when we're not concerned with OpenGL state between desmume and retroarch. 

Some shaders are also broken without a separate context, for example try nedi/nedi.glslp.

I need to identify the state that's changing during desmume's possession of the context.

**Comment by bearoso** [comment]
I'm forcing the separate context now, which in OpenGL circles is considered the correct solution anyway, so this is "fixed." I don't believe there's any extra copying going on, so it shouldn't be any slower. If it is, feel free to reopen and we'll track down the clobbered state.
