### ISSUE TITLE
Bizarre bad performance in pokemon soul silver 

### ISSUE THREAD

**Issue by WizLizard** [libretro/desmume#20]
I have a 7700k and gtx 1080 ti and at random points when using this new port i get random massive fps drops in this particular game.

**Comment by bearoso** [comment]
Is it *completely* random or at particular locations, and what are the drops like? Half-speed?

**Comment by bearoso** [comment]
Can you post a battery save at the location it drops? Pokémon let’s you save anywhere so it should be easy to save right where the performance is bad. On a 7700k you shouldn’t be getting frame drops unless it’s a giant internal resolution or something that’s part of the game.

**Comment by WizLizard** [comment]
It might have been an issue with my rom but I can't say for sure yet. I re dumped my rom last night and haven't been able to reproduce it yet. I'm going to do more testing when i get home. I'll let you know what happens.

**Comment by WizLizard** [comment]
@bearoso It only happens when i go above 11792x1344 internal resolution but the behavior is strange. I can be at full 60fps in one spot and then randomly drop to 40 in the same exact spot for maybe 10-20 second then it goes back to 60.
[saves.zip](https://github.com/libretro/desmume/files/1805927/saves.zip)

**Comment by WizLizard** [comment]
Go ahead and close, I've done thorough testing. Can no longer reproduce it.

**Comment by bearoso** [comment]
You might be seeing vsync contention--it's random like that. Make sure the disable desktop composition option in retroarch is on, and/or windowed fullscreen is off, and if you're using hard sync disable it. Try max swapchain images 2 or greater.

**Comment by WizLizard** [comment]
Swapchain is set to 2 and true fullscreen is on. Not sure if desktop composition is off I'll have to check later.
