### ISSUE TITLE
Pressing R3 crashes the core now (with layout set at quick switch)

### ISSUE THREAD

**Issue by twinaphex** [libretro/desmume#26]
As described in the subject, if I have the layout set to 'quick switch', and I then try to switch between the two layouts by pressing R3, it will cause a crash.

Testd on Windows 10 x64, using the GL renderer.

**Comment by bearoso** [comment]
I see what's going on. OpenGL is deferring the memory access, so the pointer goes invalid by the time it wants to copy the data. This happens in the frontend. I'm going to try some refactoring to get around this.

**Comment by bearoso** [comment]
This should be fixed in 77cf9a4. There was another bit of old code where it was trying to draw the non-selected screen to the buffer, but no longer got away with it because it wasn't a gigantic static buffer like before.
