### ISSUE TITLE
Rotate controls according to video rotation

### ISSUE THREAD

**Issue by Papermanzero** [libretro/desmume#29]
If the video is rotated by 90 degrees the controls stay the same. The user cannot even create custom input maps because the retropad itself must be newly configured. Also mouse controls do not work because they are also not rotated. Therefore a feature is needed to rotate the controls according to the video rotation.

Exampel: Hotel Dusk

**Comment by bearoso** [comment]
I noticed this as well. I've got a solution in mind for mouse controls, since it's just a matter of transposing the x and y deltas.

I'm not sure what you mean by the retropad needing to rotate. Is it that hotel dusk changes left/right to up/down, but since you're using a controller and not a DS, the physical controls need remapping to rotate with them?

**Comment by Papermanzero** [comment]
I changed the mapping of retropad as workaround. Means, I mapped the right analog stick up to retro pad right analog left. So I „rotated“ the input mapping. However the user cannot store game specific retro pad mappings.

**Comment by bearoso** [comment]
Added an input rotation option that can be set to the same thing as Retroarch's rotation for upright movement. Doesn't work on d-pad. 

As far as two touch points, I don't think the DS has the ability to sense more than one. If there's some game requiring two then it probably uses interpolation to hit the midpoint between the two touch points.

**Comment by Papermanzero** [comment]
Perfect. Thanks. 

Concerning mult touch.
Here an example at minute 16.
https://youtu.be/XWxY5RlJaZU

It is somehow interpolation you are right.

**Comment by Papermanzero** [comment]
Works perfect! Thanks! For the dpad a remap file can be created.
