### ISSUE TITLE
Touchscreen input mapped incorrectly in hybrid layout mode with hybrid layout scale set to 3

### ISSUE THREAD

**Issue by jdgleaver** [libretro/desmume#34]
There seems to be a touchscreen input scaling/mapping bug under the following conditions:

- Hybrid layout mode (either hybrid/top or hybrid/bottom)
- Hybrid Layout: Scale set to 3
- Hybrid Layout: Cursor Always on Small Screen OFF
- Touchscreen displayed as the (large) main screen

With this setup, the mouse cursor is drawn correctly and can be moved to any part of the touchscreen, but all input is mapped to a rectangle 1/3 the size of the touchscreen in the top left corner. The following screenshot from 'Art Academy' most clearly demonstrates the problem:

![art_academy](https://user-images.githubusercontent.com/38211560/38494856-5c45b926-3bef-11e8-83f2-f12c81b0d09a.jpg)

The dotted grey lines show where I clicked and dragged the mouse. The red 'paint' lines show where the input was registered.

The problem affects the most recent version of the core (commit 2085971) running under both Windows 7 (x64) and Linux (OpenSUSE Leap 43.3). The input mapping is correct if Hybrid Layout: Scale is set to 1.

**Comment by bearoso** [comment]
Ok, I think I fixed this, hopefully without introducing other issues.

**Comment by jdgleaver** [comment]
Thanks, that's brilliant - the input mapping works perfectly now!

(I tested all display modes/configurations and found no other issues, so all is well)
