### ISSUE TITLE
Hybrid screen layout broken

### ISSUE THREAD

**Issue by milesrotaru** [libretro/desmume#38]
Bug only occurs when hybrid scale is set to 1x. 3x looks fine. 1x was working normally until I updated the core today. I suspect it was a commit sometime within the last week. See screenshot.

![5844 - solatorobo - red the hunter usa en fr de es it ndsi enhanced -180413-125019](https://user-images.githubusercontent.com/1683975/38747672-9c32a59e-3f19-11e8-9683-0d3fbac0aa1a.png)

**Comment by bearoso** [comment]
Yep, I did something stupid again. Fixed in b444489.
