### ISSUE TITLE
Internal Resolution x3 or higher - Performance drop greatly

### ISSUE THREAD

**Issue by tabnk** [libretro/desmume#39]
Any chance to improve GL rendering performance when internal resolution is higher than x3?

**Comment by bearoso** [comment]
Make sure you’re not using hybrid mode with hybrid scale 3. I’ve done that and wondered why performance tanked when it was fine at that resolution before. It has no benefit when internal resolution is 3x or more anyway.

**Comment by tabnk** [comment]
By changing hybrid scale to 1.  Mario Kart can play at 5x internal resolution now.  Nice

**Comment by bearoso** [comment]
I've changed it so hybrid layout scale automatically disables at internal resolution factors 3 and over to prevent this from biting anyone else.
