### ISSUE TITLE
How to solve the problem in the desmume folder

### ISSUE THREAD

**Issue by luojinhui** [libretro/desmume#40]
BUILD    desmume (target)
make[1]: Entering directory '/home/luojh/Lakka-LibreELEC/build.Lakka-ROCK64.arm-2.1-devel/desmume-64230f3/desmume'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/luojh/Lakka-LibreELEC/build.Lakka-ROCK64.arm-2.1-devel/desmume-64230f3/desmume'
make: *** [image] Error 2

Because of my system is LINUX, I read the README_LIN, according to the steps on desmume/SRC/frontend/posix file:
. / autogen. Sh
. / configure
But when running "make", get wrong:
Ar: ` u 'modifier ignored since ` D' is the default (see ` u ')

Ar:.. /.. /libretro-common/file/retro_stat. O: No such file or directory.

Make [1]: *** [libdesmume. A] Error 1.

Make [1] : brigade directory ` / home/luojh/Lakka - LibreELEC/build Lakka - ROCK64. Arm - 2.1-devel/f3 / desmume desmume - 64230 / SRC/frontend/posix '

Make: *** [install-recursive] Error 1.

**Comment by bearoso** [comment]
Are you trying to build the libretro library? Because that's in src/frontend/libretro. If you're trying to build the standalone version using this repository it won't work because some of the libretro-common APIs the other ports used were changed.
