### ISSUE TITLE
Alternative view for Hybrid Mode

### ISSUE THREAD

**Issue by RyanBram** [libretro/desmume#44]
One of the nice features that RetroArch has over standalone DeSmuME is Hybrid Screen. It use unused screen area to show the entire DS Screen, so user can see the whole DS experience while enjoying bigger resolution for one screen. The current layout can be illustrated as this:
![retroarch](https://user-images.githubusercontent.com/4508389/41812469-908ecf80-774d-11e8-8923-c59a0edacae9.png)

It works very well, but if accepted, I want to request another method to show the DS screen. My suggestion is heavily inspired by how DeSmuME x432r works. The setting can be found in DeSmuME x432r under **View -> Screen Size -> 100% : 50%**. With this setting, both Top and Bottom of DS screen will looks bigger and can be arranged symmetrically. This is how it will looks:
![desmume 360x](https://user-images.githubusercontent.com/4508389/41812537-e1561f58-774e-11e8-9d46-ffeb07abebfd.png)

This alternative method will have at least 2 advantages as described above:
1. Bigger view for Top and Bottom DS screen,
2. It looks symmetrical that give impression that the entire laptop screen has filled with game display.

Thanks.

**Comment by RyanBram** [comment]
Hi.

It is about 6 months since I opened the issue and there aren't any answer yet.
So I want to bump it while updating the issue with screen mock up for what will be expected as the result:
![5096 - fire emblem - shin monshou no nazo hikari to kage no eiyuu v01 dsi enhanced j suxx -190101-100247](https://user-images.githubusercontent.com/4508389/50570146-d4138e00-0daf-11e9-926b-c42a1109ee7f.png)
This feature will make better use for available screen and make the DS Screen looks full and symmetrical compared to the current hybrid mode.

Thanks.

**Comment by bearoso** [comment]
Added this. You set hybrid layout ratio to 2:1.

**Comment by RyanBram** [comment]
Horray,
Thank you so much for your response.
I have tried it and it works as expected.

Many, many, thanks.
