### ISSUE TITLE
Assertion failed in debug mode

### ISSUE THREAD

**Issue by ghost** [libretro/desmume#7]
Using latest HEAD and RA, I get a crash on startup with this assertion when building with DEBUG=1 on both Linux and Windows 10:

```
retroarch: ../../NDSSystem.cpp:2806: void gotInputRequest(): Assertion `!validToProcessInput' failed.
```

**Comment by bearoso** [comment]
When I was debugging I avoided disabling NDEBUG because it looked like some assertions were spurious. I'll run a debug build and take a look at these and see if they can be disabled.
